### ISSUE TITLE
using null.String field to store Raw json string

### ISSUE THREAD

**Issue by yassine-y** [aarondl/sqlboiler#437]
I'm storing raw json in a data file (nullable varchar) and sqlboiler generated a Null.String field for it everything works fine for quering the table, the rows get marshalled using Google/JsonApi library, and then sent to the frontend, same reply gets sent to the backend to be saved but then the problem takes place Json fails to unmarshall the Null.String field...

I tested using *string and it worked fine for updating the DB, but then for querying SqlBoiler doesn't like that, I'm wondering what could be wrong?

The table is:
```
type MyTable struct {
	ID  uint8  `boil:"id" json:"id" jsonapi:"primary,my-table"`
	data Null.String `boil:"data" json:"data" toml:"data" yaml:"data" jsonapi:"attr,data"`

	R *appsUserR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L appsUserL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}
```

The error I get is:
**`"json: cannot unmarshal string into Go value of type map[string]interface {}"`**
Any help would be highly appreciated

**Comment by you-yas55** [comment]
Actually as mentioned the problem is when using JsonApi libraries including the Google/JsonApi one :) Json marshalling/unmarshalling itself seems to work pretty fine, matter of fact this library has been quite nice working with it, but I'm yet falling behind understanding the point from using Null.Types instead of pointers any particular reason for that? had to switch to gorm because of that unmarshalling error...

**Comment by aarondl** [comment]
Sounds like a bug with google/jsonapi. The fact that they're not calling [`UnmarshalJSON`](https://github.com/volatiletech/null/blob/master/string.go#L40) or [`UnmarshalText`](https://github.com/volatiletech/null/blob/master/string.go#L72) which are defined for string is a problem which is what allows this type to be properly serialized. You should ask them why they're circumventing the standard mechanisms. It's also possible if they have their own interface that we could enhance the null package to take advantage of that.

The reason behind not using pointers to everything is efficiency. I've gone a little crazy in the response because I want people to understand this.
Using pointers is an incredibly inefficient way to achieve "nullability" and would only be done by someone who doesn't value performance.

There are many inefficiencies that come from using pointers:

1. Tracking nullability with a pointer takes more memory
    The size of a boolean value is 1 byte, now because of struct padding you may lose some of this gain but it's at least pretending to be efficient and if you have a nice number of database fields that are nullable you may not even get a penalty for struct padding and you'll simply have a savings of say 8 bytes to store 8 field's nullability vs 64 bytes. Which do you prefer?

1. Pointers create pressure on the GC
    Every pointer in the struct adds a new place (as illustrated in the program and output below) in ram that technically belongs to this struct. For every pointer allocated (remember that sqlboiler's will allocate only one pointer per model with the exception of `decimal.Big` and any slice types) creates work for the garbage collector. The more pointers you create the more it has to work to free them later. When one decently sized model loaded from the database creates 16 pointers, that's a living hell for the garbage collector. The Go GC has gotten pretty damned good in recent years but it's not magic, your performance *will* suffer in a busy API server that's creating tons of these model objects concurrently and discarding them quickly (lifespan of a request which should be <100ms). Would you rather each API request makes 16 things for the garbage collector to do? Or one?

1. Pointers fight modern CPU architecture and cache
    When you have a chunk of memory that's contiguous, it does wonders for CPU caching (the thing that actually makes access to memory BLAZING fast). The more you can cache the better. But when you ask the CPU to grab `Fragmented` (the type in the example below), you're actually just loading a bunch of useless pointers into your cache. So accessing the pointers will be quick, but what if you want the value? Your value didn't come with Fragmented struct loading and is somewhere else off in ram. Now an additional instruction to go fetch something from ram has to occur in order to get your `ID` field. That means even basic field access is slowed down substantially. In `Contiguous` case the value is simply in the cache (probably) and therefore because you accessed ID, you get Age for free without having to do another ram lookup.

You can see in the example below the memory layout. Note that the memory where it put f.ID and f.Age are very separate: `f.id: 0xc042062058, f.age: 0xc042062080` and not separated by 4 or 8 bytes as would be proper (and is true in the `Contiguous` type).

```go
package main

import (
	"fmt"
	"reflect"
)

type Contiguous struct {
	ID  int
	Age int
}

type Fragmented struct {
	ID  *int
	Age *int
}

func main() {
	var c Contiguous
	var f Fragmented
	f.ID = new(int)
	f.Age = new(int)

	fmt.Printf("c: %p\n", &c)
	fmt.Printf("c.id: %p, c.age: %p\n", &c.ID, &c.Age)
	fmt.Printf("sizeof(c): %v\n\n", reflect.ValueOf(c).Type().Size())

	fmt.Printf("f: %p\n", &f)
	fmt.Printf("f.id: %p, f.age: %p\n", f.ID, f.Age)
	fmt.Printf("sizeof(f): %v", reflect.ValueOf(f).Type().Size())
}
```

```text
c: 0xc042062070
c.id: 0xc042062070, c.age: 0xc042062078
sizeof(c): 16

f: 0xc0420561c0
f.id: 0xc042062058, f.age: 0xc042062080
sizeof(f): 16
```

I hope I haven't overwhelmed you with this response. But hopefully you can see that if you're using many pointers in a struct for database access where null appears often it's actually really bad for performance. Using Gorm you're effectively lowering the maximum performance of your API server. How much? I'm not sure, you'd have to measure it, but I'd wager it'd be fairly dramatic given even field access requires an additional memory lookup now. Test it and let me know :)

As for helping you fix your problem I simply cannot without more information. I asked for a contained sample of the problem. That means create a small program that does just enough to reproduce the bug if you want further help. It should be extremely straightforward as you can use the null type from any random main.go, and you should be able to call unmarshal in whatever library you're using.

**Comment by you-yas55** [comment]
Really appreciate your very detailed answer, actually, I tried to get to the root of the problem and indeed Google JsonApi nor (other common jsonapi libraries tried two others), are NOT calling UnmarshalJSON/Text for the null.* types, and noticed that it tries to handle the values as structs instead, which causes it to fail with a types mismatch error trying to parse string into a struct field.

I can't make a test program right now and provide further details, but I'll do so as soon as possible :) 

**PS.** Thanks for the very detailed explanation of the reason behind null.types.
